### ISSUE TITLE
Can't use the tinker station/anvil

### ISSUE THREAD

**Issue by Blixcuh** [RedstoneChicken/Krafted#18]
Can't click on the recipe things on the tool station/anvil in tinker's construct
This issue is on mobile
![IMG_20230207_223208](https://user-images.githubusercontent.com/124733464/217358682-f8d1a844-a489-473a-a8ab-1b60f434f99d.jpg)

**Comment by RedstoneChicken** [comment]
It is not a button, its just a image to showcase what you can craft. If the original addon adds this feature we will update Krafted with it
