### ISSUE TITLE
Error Found

### ISSUE THREAD

**Issue by Swordsartonline** [RedstoneChicken/Krafted#3]
![Uploading Screenshot_20230122_222710_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

**Comment by Swordsartonline** [comment]
![Screenshot_20230122_222710_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/88285313/213921454-38ede543-1181-4c8c-8206-e17b8f87465f.jpg)

**Comment by RedstoneChicken** [comment]
Those ui errors can be ignored
